command: [
  "bash",
  "-lc",
  "pip install -r requirements.txt && streamlit run app.py"
]

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: STREAMLIT_SERVER_HEADLESS
    value: "true"
  - name: SERVING_ENDPOINT_NAME
    valueFrom: "serving-endpoint"
