command:
  - "python"
  - "-m"
  - "streamlit"
  - "run"
  - "app.py"

dependencies:
  - "requirements.txt"

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: STREAMLIT_SERVER_HEADLESS
    value: "true"
  - name: DATABRICKS_HOST
    value: "https://e2-demo-field-eng.cloud.databricks.com"
  - name: DATABRICKS_ENDPOINT_URL
    value: "https://e2-demo-field-eng.cloud.databricks.com/serving-endpoints/t2t-0f2d9d91-endpoint/invocations"
  - name: SERVING_ENDPOINT_NAME
    value: "databricks-claude-sonnet-4-5"
  - name: PGHOST
    value: "instance-d5242df0-4f16-4622-bd4f-769a93c882ee.database.cloud.databricks.com"
  - name: PGUSER
    value: "96819ea3-13c7-4975-9fa2-a204141ef034"
  - name: PGDATABASE
    value: "acndemo"
  - name: PGINSTANCE_NAME
    value: "fe-fieldkit-lakebase-not-drop"
  - name: PGPORT
    value: "5432"
  - name: PGSSLMODE
    value: "require"
  - name: PGAPPNAME
    value: "variance_analysis"
  - name: USE_SP_AUTH
    value: "true"
