command:
  - "python"
  - "-m"
  - "streamlit"
  - "run"
  - "app.py"

dependencies:
  - "requirements.txt"

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: STREAMLIT_SERVER_HEADLESS
    value: "true"
  - name: SERVING_ENDPOINT_NAME
    valueFrom: "serving-endpoint"
